if(NOT LIBSDRPLAY_FOUND)
  # pkg_check_modules (LIBSDRPLAY_PKG libsdrplay)

  if(APPLE)
    SET(LIBSDRPLAY_HEADER_NAME mir_sdr.h)
    SET(LIBSDRPLAY_LIB_NAME mir_sdr)
  else()
    SET(LIBSDRPLAY_HEADER_NAME, mirsdrapi-rsp.h)
    SET(LIBSDRPLAY_LIB_NAME, mirsdrapi-rsp)
  endif()

  find_path(LIBSDRPLAY_INCLUDE_DIRS NAMES "${LIBSDRPLAY_HEADER_NAME}"
    PATHS
    /usr/include
    /usr/local/include
  )
  # ${LIBSDRPLAY_PKG_INCLUDE_DIRS}

  find_library(LIBSDRPLAY_LIBRARIES NAMES "${LIBSDRPLAY_LIB_NAME}"
    PATHS
    /usr/lib
    /usr/local/lib
  )
  # ${LIBSDRPLAY_PKG_LIBRARY_DIRS}

if(LIBSDRPLAY_INCLUDE_DIRS AND LIBSDRPLAY_LIBRARIES)
  set(LIBSDRPLAY_FOUND TRUE CACHE INTERNAL "libsdrplay found")
  message(STATUS "Found libsdrplay: ${LIBSDRPLAY_INCLUDE_DIRS}, ${LIBSDRPLAY_LIBRARIES}")
else(LIBSDRPLAY_INCLUDE_DIRS AND LIBSDRPLAY_LIBRARIES)
  set(LIBSDRPLAY_FOUND FALSE CACHE INTERNAL "libsdrplay found")
  message(STATUS "libsdrplay not found.")
endif(LIBSDRPLAY_INCLUDE_DIRS AND LIBSDRPLAY_LIBRARIES)

mark_as_advanced(LIBSDRPLAY_LIBRARIES LIBSDRPLAY_INCLUDE_DIRS)

endif(NOT LIBSDRPLAY_FOUND)
